pin "application"
pin "jquery", to: "jquery3.min.js"
pin "popper", to: "popper.js"
pin "bootstrap", to: "bootstrap.min.js"
pin "my_utils", to: "my_utils.js"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
